apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: lab5
type: Opaque
stringData:
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_DB: "mydb"
  URL_DATABASE: "postgresql+asyncpg://myuser:mypassword@database-service/mydb"
  SECRET_KEY: "supersecretkey"
  SMTP_USER: "findyourpet9@gmail.com"
  SMTP_PASSWORD: "smtpsuperpassword"
  VITE_YMAPS_API_KEY: "ymaps-key-here"
  VITE_YMAPS_GEOSUGGEST_API_KEY: "ymaps-suggest-key-here"
  VITE_IMAGE_UPLOADER_API_KEY: "img-uploader-key-here"
