apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: lab5
type: Opaque
stringData:
  POSTGRES_USER: "docker"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: "findyourpet"
  URL_DATABASE: "postgresql+asyncpg://docker:1234@database-service:5432/findyourpet"
  SECRET_KEY: "ai0d0a8hh029q-djq9-djq90d280dh0qdniqwdnq082d2nq2nd99"
  SMTP_USER: "findyourpet9@gmail.com"
  SMTP_PASSWORD: "bzgcxwexxynuoium"
  VITE_YMAPS_API_KEY: "1b6ee47b-d941-482e-8b6a-7f71a6dc8f30"
  VITE_YMAPS_GEOSUGGEST_API_KEY: "496897cf-b795-4baa-815a-513b67e95941"
  VITE_IMAGE_UPLOADER_API_KEY: "5503fcf82407810eb9f88083c2799adf"
