apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: lab5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec:
      containers:
        - name: backend
          image: lab5-backend:1.6
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "findyourpet-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: lab5
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
